a = int(input('Enter your first number: '))
b= int(input('Enter your second number: '))
print('{} + {} = '.format(a, b))
print(a + b)
print('{} - {} = '.format(a, b))
print(a - b)
print('{} * {} = '.format(a, b))
print(a * b)
print('{} / {} = '.format(a, b))
print(a / b)